# Generated by Django 4.2.4 on 2023-08-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('localidade', models.CharField(max_length=200)),
                ('estado_civil', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=200)),
                ('operadora', models.CharField(max_length=20)),
                ('date_nascimento', models.DateField()),
                ('data_batismo', models.DateField()),
                ('inicio_gem', models.DateField()),
            ],
        ),
    ]
