# Generated by Django 4.2.4 on 2023-08-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumento',
            options={'verbose_name': 'Instrumento', 'verbose_name_plural': 'Instrumentos'},
        ),
    ]
